### PR TITLE
Now publishes interesting images

### PR DESCRIPTION
**Pull request by jim-v**
Can optionally publish images that are deemed interesting by the library.  This is a debugging tool.

### CODE REVIEW

**Comment by trainman419** [comment]
You've removed `launch/fiducials_rviz.launch`, and there are some other interesting artifacts in your commit history.

It looks like you need to rebase this on top of master: http://git-scm.com/book/en/Git-Branching-Rebasing

**Comment by waynegramlich** [comment]
Austin:

I more or less swore off of rebasing because:

> The Perils of Rebasing
> 
> Ahh, but the bliss of rebasing isn’t without its drawbacks, which can be summed up in a single line:
> 
> Do not rebase commits that you have pushed to a public repository.
> 
> If you follow that guideline, you’ll be fine. If you don’t, people will hate you, and you’ll be scorned by friends and family.

I must be missing something....  No, need for an E-mail response,
I'll ask the question the next time I see you...

Regards,

-Wayne

**Comment by jim-v** [comment]
Sorry about that I don't think it was fixable by reabasing, but the launch
file is back.

**Comment by trainman419** [comment]
Superceded by #15

**Pull request closed without merging**
